"""Derive the motorcycle fit dataset from static/vehicleData.js.

Run from the project root:   python tools/build_bike_fit.py

Seat heights already live in `motoData` because the comparison page needs
them. Copying them into a second hand-maintained file would guarantee the two
drift apart, so this generates `content/fit-guides/bike-fit-data.json` from
that one source instead — the same reasoning behind build_site.py lifting the
legal copy straight out of app.py.

Re-run it whenever bikes are added to vehicleData.js.
"""
import json
import os
import re
import sys

SRC = os.path.join("static", "vehicleData.js")
OUT = os.path.join("content", "fit-guides", "bike-fit-data.json")

# Inseam bands. Seat height is only a proxy for whether you can get a foot
# down — see the caveats in the guide prose — so these are deliberately coarse
# bands rather than a precise cutoff.
BANDS = [
    {"key": "short",  "label": "Under 29\" inseam",  "sub": "Riders around 5'4\" and under",
     "max": 760},
    {"key": "mid",    "label": "29–32\" inseam",      "sub": "Riders roughly 5'5\"–5'11\"",
     "min": 760, "max": 815},
    {"key": "tall",   "label": "32\"+ inseam",        "sub": "Riders 6' and over",
     "min": 815},
]


def parse_moto_data(src):
    """Pull the object literals out of the motoData array.

    A regex rather than a JS parser: the entries are uniform one-line literals,
    and the assertion on the total count below catches the case where that
    stops being true.
    """
    start = src.index("const motoData")
    end = src.index("];", start)
    block = src[start:end]

    entries = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("{") or "make:" not in line:
            continue
        rec = {}
        for key, val in re.findall(r'(\w+)\s*:\s*"([^"]*)"', line):
            rec[key] = val
        for key, val in re.findall(r'(\w+)\s*:\s*(-?\d+(?:\.\d+)?)\s*[,}]', line):
            rec[key] = float(val) if "." in val else int(val)
        if rec.get("make") and rec.get("model"):
            entries.append(rec)
    return entries


def band_for(mm):
    for b in BANDS:
        if mm >= b.get("min", 0) and mm < b.get("max", 10 ** 6):
            return b["key"]
    return None


def main():
    if not os.path.exists(SRC):
        sys.exit("Run this from the project root — %s not found." % SRC)

    bikes = parse_moto_data(open(SRC, encoding="utf-8").read())
    if len(bikes) < 50:
        sys.exit("Only parsed %d bikes; the motoData format has probably "
                 "changed and this extractor needs updating." % len(bikes))

    measured = [b for b in bikes if b.get("seat_height_mm")]
    out = []
    for b in sorted(measured, key=lambda b: b["seat_height_mm"]):
        mm = b["seat_height_mm"]
        out.append({
            "make": b["make"],
            "model": b["model"],
            "type": b.get("type") or "",
            "seatHeightMm": mm,
            # Riders shop in inches; one decimal is as precise as the
            # underlying spec justifies.
            "seatHeightIn": round(mm / 25.4, 1),
            "weightKg": b.get("weight_kg"),
            "band": band_for(mm),
        })

    data = {
        "_comment": [
            "GENERATED by tools/build_bike_fit.py — do not edit by hand.",
            "Source of truth is motoData in static/vehicleData.js.",
            "Re-run the script after adding bikes there.",
        ],
        "bands": BANDS,
        "totalBikes": len(bikes),
        "measured": len(measured),
        "bikes": out,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    print("%d bikes parsed, %d with a seat height -> %s"
          % (len(bikes), len(measured), OUT))
    missing = len(bikes) - len(measured)
    if missing:
        makes = {}
        for b in bikes:
            if not b.get("seat_height_mm"):
                makes[b["make"]] = makes.get(b["make"], 0) + 1
        print("%d still unmeasured: %s" % (
            missing, ", ".join("%s x%d" % (k, v)
                               for k, v in sorted(makes.items()))))


if __name__ == "__main__":
    main()
